project:
  type: website
  output-dir: docs

website:
  title: "Social Network Analysis for Newbies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href:  https://github.com/laser-institute/LAK24-kyoto-SNA
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Prior to workshop"
        contents: 
          - pre_workshop/Welcome.qmd
          - pre_workshop/laser_toolkit.qmd
      - section: "Part 1"
        contents: 
          - part1/part1_index.qmd
      - section: "Part II"
        contents:
          - part2/part2_index.qmd
      - section: "More SNA Cases"
        contents:
      - section: "Post Workshop"
        contents:
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual
